import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "easymde/dist/easymde.min.css";
import Sidebar from "@/components/Sidebar";
import UserItem from "@/components/UserItem";
import { ThemeProvider as NextThemeProvider } from "next-themes";
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from "@/components/ui/resizable";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">

			<body className={inter.className}>
			  <NextThemeProvider attribute="class" defaultTheme="light" enableSystem>
				<ResizablePanelGroup
					direction="horizontal"
					className="min-h-[900px] h-screen w-full rounded-lg border"
				>
					<ResizablePanel defaultSize={25} minSize={20}>
						<UserItem />
						<Sidebar />
					</ResizablePanel>
					<ResizableHandle withHandle />
					<ResizablePanel defaultSize={75}>
					<main className="flex-grow">
          <Header />
					<div className="p-4">
          {children}
					</div>
        </main>
					</ResizablePanel>
				</ResizablePanelGroup>
			</NextThemeProvider>
			</body>

		</html>
	);
}
