import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "easymde/dist/easymde.min.css";
import Sidebar from "@/components/Sidebar";
import UserItem from "@/components/UserItem";
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from "@/components/ui/resizable";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ResizablePanelGroup
					direction="horizontal"
					className="min-h-[900px] h-screen w-full rounded-lg border"
				>
					<ResizablePanel defaultSize={25} minSize={20}>
						<UserItem />
						<Sidebar />
					</ResizablePanel>
					<ResizableHandle withHandle />
					<ResizablePanel defaultSize={75}>
						<div className="flex flex-col h-full justify-center p-6">
							{children}
						</div>
					</ResizablePanel>
				</ResizablePanelGroup>
			</body>
		</html>
	);
}
